### ISSUE TITLE
Replace hashmap dispatch with multi-method or other polymorphism

### ISSUE THREAD

**Issue by bsless** [fctorial/parse_struct#1]
Hi,
Interesting project.

There's a "free" optimization you can do for JVM processes, which is replacing the map dispatch, for example deserializer `parsers` and `intParsers` with multimethods. That way you can benefit from the JVMs JIT which should theoretically give better performance, although you still pay a bit for the indirection involved. Even faster would be to define protocols and records.

example:
```clojure
(defmulti parse :type)
(defmethod parse :float  [{bc :bytes} data]
  (let [bb (.order (ByteBuffer/wrap (byte-array (take-exactly bc data))) ByteOrder/LITTLE_ENDIAN)]
   (case bc
     4 (.getFloat bb)
     8 (.getDouble bb)
     (throw (new IllegalArgumentException "Floats can have 4 or 8 bytes"))))
```

Cheers

**Comment by fctorial** [comment]
I implemented multimethods ([multimethods](https://github.com/fctorial/parse_struct/tree/multimethods)), but there was no visible performance improvement (run benchmarks with `clojure -A:test`).

All the maps used for dispatching are small in size (upto 6-8), and I think clojure will turn them into `PersistentArrayMap`, which do lookups with a for loop. This lookup could be sped up a bit by using `:2`, `:4` instead of `2`, `4`, but the library uses `(* size 8)` in some places, so it might require some refactoring.

Another optimization that could improve performance is writing separate parsers for `i8`, `u8`, ... ,`i64`, `u64`, `f32`, `f64`, and dispatching on the reference identity of primitives defined in `parse_struct.common-types`. Metaprogramming and macros might help here.

**Comment by bsless** [comment]
I'm not sure 3 iterations are enough, or that just one big dataset is indicative.
Have you tried comparing the implementations with criterium?
I don't want you to feel like I'm nitpicking you because I'm still breaking my teeth on the whole JVM benchmarking thing, but the results really vary based on how I benchmarked my things. Different implementation might even be faster for different types and sizes of inputs, and there's no way to find it out besides scanning the input space and analyzing the results.

**Comment by fctorial** [comment]
The 3 iteations have 10000 iterations of same code inside them. I tried 10 iterations, but the results were same.

Benchmarking with different datasets could give different results, but that would require adding support for seed in random struct generator. The current dataset is of reasonable size, and contains all of the supported types, which is why I used it.

I will be using the multimethods anyway because they fit the use case perfectly and got rid of `declare` statements. Thanks for that.
